package workspace

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type Report struct {
	GeneratedAgents bool
	Warnings        []string
}

const bridge = `# Codex Workspace Bridge

This file is generated by codex_workspace_bot when AGENTS.md is missing.

Read CLAUDE.md as the legacy workspace instruction source, then follow
Codex-native rules from this file when they conflict.

Framework context for each turn is written to SESSION_CONTEXT.md.
`

func Init(root, appID string) (Report, error) {
	var report Report
	for _, rel := range []string{".codex", ".codex/skills", ".claude/skills", "memory", "tasks", "sessions"} {
		if err := os.MkdirAll(filepath.Join(root, rel), 0o755); err != nil {
			return report, fmt.Errorf("创建目录 %s: %w", rel, err)
		}
	}
	lock := filepath.Join(root, ".memory.lock")
	if _, err := os.Stat(lock); os.IsNotExist(err) {
		if err := os.WriteFile(lock, []byte(""), 0o644); err != nil {
			return report, fmt.Errorf("创建 memory lock: %w", err)
		}
	}
	agents := filepath.Join(root, "AGENTS.md")
	if _, err := os.Stat(agents); os.IsNotExist(err) {
		if err := os.WriteFile(agents, []byte(bridge), 0o644); err != nil {
			return report, fmt.Errorf("创建 AGENTS.md bridge: %w", err)
		}
		report.GeneratedAgents = true
	}
	feishuConfig := filepath.Join(root, ".claude", "skills", "feishu_ops", "feishu.json")
	if _, err := os.Stat(feishuConfig); err == nil {
		_ = os.Chmod(feishuConfig, 0o600)
	}
	warnings, err := detectMalformedSkills(root, appID)
	if err != nil {
		return report, err
	}
	report.Warnings = warnings
	return report, nil
}

func detectMalformedSkills(root, appID string) ([]string, error) {
	var warnings []string
	base := filepath.Join(root, ".claude", "skills")
	err := filepath.WalkDir(base, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() || filepath.Base(path) != "SKILL.md" {
			return err
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		text := string(data)
		if !strings.HasPrefix(text, "---\n") || !strings.Contains(text, "\nname:") {
			rel, _ := filepath.Rel(root, path)
			warnings = append(warnings, fmt.Sprintf("app=%s skill=%s malformed SKILL.md", appID, rel))
		}
		return nil
	})
	return warnings, err
}
